### ISSUE TITLE
Needs update to latest snowpack api: buildOptions.out & mount.url

### ISSUE THREAD

**Issue by longlostbro** [fansenze/snowpack-plugin-inliner#3]
Steps: reproducible from repo https://github.com/longlostbro/snowpack-test

1. npx create-snowpack-app myApp --template @snowpack/app-template-react-typescript
2. npm install -D snowpack-plugin-inliner
3. add snowpack-plugin-inliner to snowpack config
4. add a png file to your project: logo.png
5. to the top of App.js add: import logo from "logo.png"
6. npm run build: get below error

> C:\Users\longl\Downloads\snowpack\myApp>npm run build
> @ build C:\Users\longl\Downloads\snowpack\myApp
> snowpack build
[11:42:23] [snowpack-plugin-inliner] Command completed.
[11:42:23] [snowpack] ! building files...
[11:42:24] [snowpack] Build Result Error: There was a problem with a file build result.
[11:42:24] [snowpack] dir.endsWith is not a function
[11:42:24] [snowpack] TypeError: dir.endsWith is not a function
    at Object.load (C:\Users\longl\Downloads\snowpack\myApp\node_modules\snowpack-plugin-inliner\plugin.js:105:51)
    at async runPipelineLoadStep (C:\Users\longl\Downloads\snowpack\myApp\node_modules\snowpack\lib\cjs\build\build-pipeline.js:40:32)
    at async Object.buildFile (C:\Users\longl\Downloads\snowpack\myApp\node_modules\snowpack\lib\cjs\build\build-pipeline.js:240:24)
    at async C:\Users\longl\Downloads\snowpack\myApp\node_modules\snowpack\lib\cjs\build\file-builder.js:204:37
    at async FileBuilder.build (C:\Users\longl\Downloads\snowpack\myApp\node_modules\snowpack\lib\cjs\build\file-builder.js:216:32)
    at async Object.loadUrl (C:\Users\longl\Downloads\snowpack\myApp\node_modules\snowpack\lib\cjs\commands\dev.js:626:17)
    at async flushFileQueue (C:\Users\longl\Downloads\snowpack\myApp\node_modules\snowpack\lib\cjs\build\process.js:191:24)
    at async Object.buildFiles (C:\Users\longl\Downloads\snowpack\myApp\node_modules\snowpack\lib\cjs\build\process.js:226:5)
    at async build (C:\Users\longl\Downloads\snowpack\myApp\node_modules\snowpack\lib\cjs\commands\build.js:11:5)
    at async Object.command (C:\Users\longl\Downloads\snowpack\myApp\node_modules\snowpack\lib\cjs\commands\build.js:35:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `snowpack build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\longl\AppData\Roaming\npm-cache\_logs\2021-08-11T14_41_24_020Z-debug.log

**Comment by longlostbro** [comment]
added a PR with working fix https://github.com/fansenze/snowpack-plugin-inliner/pull/4

**Comment by fansenze** [comment]
thx for your pr.
released 1.0.3
